
var data = { "questions" : [
    { "cat" : "Maths/Matrices", "q" : "`[[0,0,0]]` is a ", "a" : ["Unit Matrix", "Scalar Matrix", "Null Matrix", "Diagonal Matrix" ], "ca" : 2 },
	     { "cat" : "Maths/Matrices", "q" : "`[[6, 2, -3]]` is a matrix of order", "a" : ["3x3", "3x1", "1x3", "Scalar Matrix" ], "ca" : 2 },
    { "cat" : "Maths/Matrices", "q" : "`((1,0),(0,1))` is a ", "a" : ["Unit Matrix", "Zero Matrix of order 2x2", "Unit matrix of 2x2", "None of these" ], "ca" : 0 },
{ "cat" : "Maths/Matrices", "q" : "A = `((3, -3),(2, 4))` and B = `((1,2),(-1,0))`, then A + B is ", "a" : ["`((4,5),(3,4))`", "`((4,-1),(-1,4))`", "`((4,-1),(1,4))`", "`((1,0),(0,1))`" ], "ca" : 2 },
{ "cat" : "Maths/Matrices", "q" : "If A = `((8, 9), (-3, -1))` and B = `((-1, 3), (0, -2))`, then A - B is", "a" : ["`((7,6),(-3,-3))`", "`((9,6),(-3,1))`", "`((7,6),(0,1))`", "`((0,0),(0,0))`" ], "ca" : 1 },
{ "cat" : "Maths/Matrices", "q" : "If A = `((2,4),(-3,-3))`, then -3A is", "a" : ["`((-6, -12),(-9,15))`", "`((-6,-12),(9.15))`", "`((-6, 12),(9.9))`", "None of these" ], "ca" : 1 },
{ "cat" : "Maths/Matrices", "q" : "If A = `((2,3,4),(1,-1,0),(5,-3,1))` and I = `((1,0,0),(0,1,0),(0,0,1))`, then A + 2I is", "a" : ["`((4,3,4),(1,1,0),(5,-3,3))`", "`((3,3,4),(1,0,0),(5,-3,2))`", "`((4,3,4),(1,-1,0),(5,-3,2))`", "None of these" ], "ca" : 0 },
{ "cat" : "Maths/Matrices", "q" : "`((3,5,6),(-2,1,6)) x ((5,-1,0),(3,2,1))`", "a" : ["`((15,12),(-4,1))`", "`((-3,15),(8,-3))`", "Cannot be multiplied", "None of these" ], "ca" : 2 },
{ "cat" : "Maths/Matrices", "q" : "The value of `((1, -1),(0,0))` is", "a" : ["4", "14", "-14", "None of these" ], "ca" : 3 },
{ "cat" : "Maths/Matrices", "q" : "The value of `[[1,-1],[0,0]]` is", "a" : ["0", "-1", "1", "None of these" ], "ca" : 0 },
{ "cat" : "Maths/Matrices", "q" : "If the value of `[[1,2],[3,4]] = -2`, then the value of `[[1,3],[2,4]]` is", "a" : ["0", "-2", "2", "None of these" ], "ca" : 1 },
{ "cat" : "Maths/Matrices", "q" : "Det (AB) = |AB| = ?", "a" : ["|A| + |B|", "|B| + |A|", "|A| x |B|", "None of these" ], "ca" : 2 },
{ "cat" : "Maths/Matrices", "q" : "The element at 2nd Row and 2nd Column is denoted by", "a" : ["`a_(12)`", "`a_(32)`", "`a_(22)`", "`a_(11)`" ], "ca" : 2 },
{ "cat" : "Maths/Matrices", "q" : "Order of the matrix A = `[a_(ij)]_(3x3)` is", "a" : ["2x3", "3x3", "1x3", "3x1" ], "ca" : 1 },
{ "cat" : "Maths/Matrices", "q" : "When the number of rows and the number of coloumns of a matrix are equal, the matrix is", "a" : ["Square matrix", "Row matrix", "Column matrix", "None of these" ], "ca" : 0 },
{ "cat" : "Maths/Matrices", "q" : "If all the elements of a matrix are zeros, then the matrix is a", "a" : ["Unit Matrix", "Square matrix", "Zero matrix", "None of these" ], "ca" : 2 },
{ "cat" : "Maths/Matrices", "q" : "A diagonal matrix in which all the diagonal elements are equal is a", "a" : ["Scalar Matrix", "Column matrix", "Unit matrix", "None of these" ], "ca" : 0 },
{ "cat" : "Maths/Matrices", "q" : "If any two rows and coloumns of a determinant are identical, the value of the determinant is", "a" : ["1", "0", "-1", "ulaltered" ], "ca" : 1 },
{ "cat" : "Maths/Matrices", "q" : " If there is only one column in a matrix, it is called", "a" : ["Row matrix", "Column matrix", "Suqare matrix", "Rectangular" ], "ca" : 1 },
{ "cat" : "Maths/Matrices", "q" : "Addition of matrices is", "a" : ["not commutative", "commutative", "not associative", "distributive" ], "ca" : 1 },
{ "cat" : "Maths/Matrices", "q" : "A square matrix A is said to be non-singular if", "a" : ["|A| `!=` 0", "|A| = 0", "A = 0", "None of these" ], "ca" : 0 },
{ "cat" : "Maths/Matrices", "q" : "The value of x if `[[1,x],[5,3]] = 0` is", "a" : ["`5/3`", "`3/5`", "0", "None of these" ], "ca" : 1 },
{ "cat" : "Maths/Matrices", "q" : "If `[[4,8],[-9,4] = 88`, then the value of `[[8,4],[4,-9]]` is", "a" : ["-88", "88", "80", "None of these" ], "ca" : 0 },
{ "cat" : "Maths/Matrices", "q" : "The value of `[[2,6],[2,4]]` is", "a" : ["0", "-1", "1", "None of these" ], "ca" : 0 },
{ "cat" : "Maths/Matrices", "q" : "If `[[1,3],[2,4]] = -2`, then the value of `[[2,6],[2,4]]` is", "a" : ["-2", "2", "-4", "None of these" ], "ca" : 2 },
{ "cat" : "Maths/Matrices", "q" : "If `(A+B)(A-B) = A^2 - B^2` and A and B are square matrices, then", "a" : ["`(AB)^T = AB`", "AB = BA", "`(A+B)^T = B^T + A^T", "None of these" ], "ca" : 1 },
{ "cat" : "Maths/Matrices", "q" : "`((10, 10),(10,10)` is a", "a" : ["Rectangular matrix", "Scalar matrix", "Identity matrix", "None of these" ], "ca" : 3 },
{ "cat" : "Maths/Matrices", "q" : "`(1,2,6,7)` is a ", "a" : ["Square matrix", "Row matrix", "Scalar matrix", "Column matrix" ], "ca" : 3 },
{ "cat" : "Maths/Matrices", "q" : "If A = I, then `A^2`", "a" : ["`I^2`", "I", "0", "None of these" ], "ca" : 1 },
{ "cat" : "Maths/Matrices", "q" : "If A = `(1,2,3)` and B = `((1),(2),(3))`, then the order of AB is", "a" : ["1x1", "1x3", "3x1", "3x3" ], "ca" : 0 },
{ "cat" : "Maths/Algebra", "q" : "If n! = 24, then n is", "a" : ["4", "3", "4!", "1" ], "ca" : 0 },
{ "cat" : "Maths/Algebra", "q" : "The value of 3! + 2! + 1! + 0! Is", "a" : ["10", "6", "7", "9" ], "ca" : 0 },
{ "cat" : "Maths/Algebra", "q" : "The value of `1/(4!) + 1/(3!)` is", "a" : ["`5/20`", "`5/24`", "`7/12`", "`1/7`" ], "ca" : 1 },
{ "cat" : "Maths/Algebra", "q" : "The total number of ways of analysing 6 persons around a table is", "a" : ["6", "5", "6!", "5!" ], "ca" : 1 },
{ "cat" : "Maths/Algebra", "q" : "The value of x(x-1) (x-2)! Is", "a" : ["x!", "(x-1)!", "(x-2)!", "(x+1)!" ], "ca" : 0 },
{ "cat" : "Maths/Algebra", "q" : "2 persons can occupy 7 places in ____ ways", "a" : ["42", "14", "21", "7" ], "ca" : 0 },
{ "cat" : "Maths/Algebra", "q" : "The value of `.^8p_3` is", "a" : ["8 x 7 x 6", "`(8 x 7 x 6)/(3 x 2 x 1)`", "8 x 7", "3 x 2 x 1" ], "ca" : 0 },
{ "cat" : "Maths/Algebra", "q" : "The value of `.^8C_0` is", "a" : ["8", "1", "7", "0" ], "ca" : 1 },
{ "cat" : "Maths/Algebra", "q" : "The value of `.^10C_9 is", "a" : ["9", "1", "`^.10C_1`", "0" ], "ca" : 2 },
{ "cat" : "Maths/Algebra", "q" : "Number of lines that can be drawn using 5 points in which none of 3 points are collinear is", "a" : ["10", "20", "5", "1" ], "ca" : 0 },
{ "cat" : "Maths/Algebra", "q" : "If `((5),(x)) + ((5),(4)) = ((6),(5))`, then x is", "a" : ["5", "4", "6", "0" ], "ca" : 0 },
{ "cat" : "Maths/Algebra", "q" : "If `.^10C_r = .^10C_(4r)`, then r is", "a" : ["2", "4", "10", "1" ], "ca" : 0 },
{ "cat" : "Maths/Algebra", "q" : "Sum of all the binomial coefficients is", "a" : ["`2^n`", "`b^n`", "2n", "n" ], "ca" : 0 },
{ "cat" : "Maths/Algebra", "q" : "The last term in `(x+1)^n` is", "a" : ["`x^n`", "`b^n`", "n", "1" ], "ca" : 1 },
{ "cat" : "Maths/Algebra", "q" : "The number of terms in `(2x + 5)^7` is", "a" : ["2", "7", "8", "14" ], "ca" : 2 },
{ "cat" : "Maths/Algebra", "q" : "The middle term in `(x + a)^8` is", "a" : ["`t_4`", "`t_5`", "`t_6`", "`t_3`" ], "ca" : 1 },
{ "cat" : "Maths/Algebra", "q" : "The general term in `(x + a)^n` is denoted by", "a" : ["`t_n`", "`t_t`", "`t_(t-1)`", "`t_(t+1)`" ], "ca" : 3 }
]
};
